### ISSUE TITLE
The switch version option is shown on every treeview

### ISSUE THREAD

**Issue by aulMasa** [TOMIVERGARA/vscode-fontawesome-gallery#3]
![image](https://user-images.githubusercontent.com/49903778/158157760-a9ded21a-6dd5-40f3-8d68-e5cc7e866218.png)

```
         {
          "command": "vscode-fontawesome-gallery.switch-version-5",
          "when": "view == vscode-fontawesome-gallery-sidebar && vscode-fontawesome-gallery.faVersion == 6 || !vscode-fontawesome-gallery.faVersion",
          "group": "a@1"
        },
```

maybe it should be
`"when": "view == vscode-fontawesome-gallery-sidebar && ( vscode-fontawesome-gallery.faVersion == 6 || !vscode-fontawesome-gallery.faVersion )",`

**Comment by TOMIVERGARA** [comment]
Thank you so much for pointing out the problem. Sadly it couldn't be fixed in the way you suggested, so a new, alternative solution has been implemented on the latest release `0.0.7` along with support for Font Awesome v6.1.0.
I'll keep working to get the original implementation to work properly, but till then this will have to do it.
